import type { ContentModelSource } from "./validateContent.ts";

const sourceRef = {
  document: "PCT 2026 - Sebdec.docx",
  blockType: "table",
  blockIndex: 1,
} as const;

export function createValidContentModel(): ContentModelSource {
  return {
    sourceDocuments: [
      {
        id: "pct-2026-word-source",
        filename: "PCT 2026 - Sebdec.docx",
        sha256:
          "f57f19abb6360609f7f517ea53c1acbd824ef6a69faed3b599911800fd81eb4d",
        sizeBytes: 109_513_518,
        counts: {
          bodyBlocks: 993,
          paragraphs: 795,
          tables: 198,
          documentSections: 1,
          trailEntries: 2,
          postTrailEntries: 1,
          gearItems: 1,
          glossaryConcepts: 1,
          photoPlacements: 1,
          mediaAssets: 1,
        },
      },
    ],
    extractionReports: [
      {
        sourceDocumentId: "pct-2026-word-source",
        generator: "scripts/content/word/extractWordJournal.ts",
        counts: {
          trailEntries: 2,
          postTrailEntries: 1,
          gearItems: 1,
          glossaryConcepts: 1,
          photoPlacements: 1,
          mediaAssets: 1,
          reusedMediaAssets: 0,
          trailPhotoPlacements: 1,
          postTrailPhotoPlacements: 0,
          pagePhotoPlacements: 0,
          trailEntriesWithoutPhotos: 1,
        },
        validations: {
          sourceHashVerified: true,
          structuralCountsVerified: true,
          declaredMilesVerified: true,
          displayedKilometersVerified: true,
          trailMileageContinuous: true,
          mediaRelationshipsMatched: true,
          contentModelValidated: true,
        },
        structuralExceptions: [],
      },
    ],
    regions: [
      {
        id: "desert",
        order: 1,
        trailMarkKey: "cactus",
        published: true,
        sourceRefs: [sourceRef],
      },
      {
        id: "sierra",
        order: 2,
        trailMarkKey: "mountain",
        published: true,
        sourceRefs: [sourceRef],
      },
      {
        id: "norcal",
        order: 3,
        trailMarkKey: "bear",
        published: true,
        sourceRefs: [sourceRef],
      },
      {
        id: "oregon",
        order: 4,
        trailMarkKey: "lake-mosquito",
        published: true,
        sourceRefs: [sourceRef],
      },
      {
        id: "washington",
        order: 5,
        trailMarkKey: "mountain-goat",
        published: true,
        sourceRefs: [sourceRef],
      },
    ],
    sections: [
      {
        id: "section-california-a",
        code: "A",
        regionId: "desert",
        mileStart: 0,
        mileEnd: 15,
        properName: "Campo to Lake Morena",
        published: true,
        sourceRefs: [sourceRef],
      },
      {
        id: "section-california-b",
        code: "B",
        regionId: "sierra",
        mileStart: 15,
        mileEnd: 30,
        properName: "Lake Morena to the Sierra",
        published: true,
        sourceRefs: [sourceRef],
      },
    ],
    days: [
      {
        id: "day-001",
        sequence: 1,
        date: "2026-04-18",
        kind: "trail",
        regionId: "desert",
        sectionIds: ["section-california-a"],
        mileStart: 0,
        mileEnd: 10,
        ascentMeters: 751,
        descentMeters: 684,
        locationId: "campo",
        published: true,
        sourceRefs: [sourceRef],
      },
      {
        id: "day-002",
        sequence: 2,
        date: "2026-04-19",
        kind: "trail",
        regionId: "sierra",
        sectionIds: ["section-california-a", "section-california-b"],
        mileStart: 10,
        mileEnd: 20,
        ascentMeters: 500,
        descentMeters: 200,
        locationId: "lake-morena",
        published: true,
        sourceRefs: [sourceRef],
      },
      {
        id: "day-003",
        sequence: 3,
        date: "2026-07-24",
        kind: "post-trail",
        published: true,
        sourceRefs: [sourceRef],
      },
    ],
    journalEntries: [
      {
        dayId: "day-001",
        locale: "fr",
        title: "Le départ",
        locationLabel: "Campo",
        photoIds: ["photo-001001"],
        sourceRefs: [sourceRef],
      },
      {
        dayId: "day-002",
        locale: "fr",
        title: "2 sections",
        locationLabel: "Lake Morena",
        photoIds: [],
        sourceRefs: [sourceRef],
      },
      {
        dayId: "day-003",
        locale: "fr",
        title: "Après le terminus",
        locationLabel: "Vancouver",
        photoIds: [],
        sourceRefs: [sourceRef],
      },
    ],
    photos: [
      {
        id: "photo-001001",
        dayId: "day-001",
        order: 0,
        assetKey: "pct-2026-day-001-001",
        width: 1600,
        height: 1200,
        published: true,
        sourceRefs: [{ ...sourceRef, blockType: "image" }],
      },
    ],
    localizedPhotos: [
      {
        photoId: "photo-001001",
        locale: "fr",
        alt: "Le monument du terminus sud à Campo",
      },
    ],
    glossaryConcepts: [
      {
        id: "trail-angel",
        published: true,
        sourceRefs: [sourceRef],
      },
    ],
    localizedGlossaryEntries: [
      {
        conceptId: "trail-angel",
        locale: "fr",
        term: "Trail angel",
        definition: "Une personne qui aide les marcheurs sur le parcours.",
        aliases: [],
      },
    ],
    gearItems: [
      {
        id: "gear-shelter-plex-solo",
        categoryId: "shelter",
        brand: "Zpacks",
        model: "Plex Solo",
        weightGrams: 395,
        published: true,
        sourceRefs: [sourceRef],
      },
    ],
    localizedGearEntries: [
      {
        gearItemId: "gear-shelter-plex-solo",
        locale: "fr",
        name: "Tente Plex Solo",
      },
    ],
    supportingPages: [
      {
        pageId: "closing",
        locale: "fr",
        kind: "closing",
        title: "Après le chemin",
        published: true,
        sourceRefs: [sourceRef],
      },
    ],
    corrections: [
      {
        id: "correction-0001",
        entityType: "day",
        entityId: "day-001",
        field: "locationId",
        sourceValue: "Camp",
        correctedValue: "Campo",
        reason: "Correction du nom du terminus sud.",
        status: "approved",
        sourceRef,
      },
    ],
  };
}
